const games = [
    {
        "id":"g01",
        "nombre": "Helldivers 2",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717455342/imagen_2024-06-03_185538264_lrqbjq.png",
        "desarrolladores": "ArrowHead Studios",
        "genero":"Co-op Shooter",
        "descripcion":"Helldivers 2 es un juego de disparos multijugador online en el que te unes a un escuadrón con un máximo de tres amigos, así que no hay modos de juego offline o de un solo jugador.",
        "precio": 40000,
    },
    {
        "id":"g02",
        "nombre": "Elden Ring",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717455407/imagen_2024-06-03_185642006_q55edq.png",
        "desarrolladores": "Fromsoftware",
        "genero":"RPG Mundo abierto",
        "descripcion":"Elden Ring es un juego de mundo abierto en el que explorar el mundo de las tierras intermedias, descubre una gran variedad de enemigos, jefes, armas y secretos en tu camino a convertirte en el Elden Lord.",
        "precio": 60000,
    },
    {
        "id":"g03",
        "nombre": "Cyberpunk 2077",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717455450/imagen_2024-06-03_185726457_vtq7vq.png",
        "desarrolladores": "CD Projekt",
        "genero":"Shooter RPG Mundo Abierto",
        "descripcion":"Cyberpunk 2077 se situa en un futuro de tematica Cyberpunk, dentro de Night City, California, Donde tomas el papel de V, un mercenario que ha terminado con biochip ajeno implantado, que amenaza con terminar su vida.",
        "precio": 60000,
    },
    {
        "id":"g04",
        "nombre": "Monster Hunter World",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717455506/imagen_2024-06-03_185822096_s7l7hz.png",
        "desarrolladores": "Capcom",
        "genero":"Co-op RPG de accion",
        "descripcion":"Participa en cacerias de increibles bestias que habitan el mundo de Monster Hunter World con hasta otros 3 cazadores, utliza tus recompensas para mejorar tu equipamiento y vuelve a cazar monstruos aun mas grandes.",
        "precio": 30000,
    },
    {
        "id":"g05",
        "nombre": "The Legend Of Zelda: Tears Of The Kingdom",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717455541/imagen_2024-06-03_185857475_svxjr7.png",
        "desarrolladores": "Nintendo",
        "genero":"Mundo abierto aventura",
        "descripcion":"Explora el vasto mundo de Hyrule en busca de la clave de salvarlo de las fuerzas malignas de Ganondorf, resuelve puzzles, conoce interesantes personajes y se el heroe que Hyrule necesita",
        "precio": 60000,
    },
    {
        "id":"g06",
        "nombre": "Super Smash Bros. Ultimate",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717454820/imagen_2024-06-03_184430059_itmjyg.png",
        "desarrolladores": "Nintendo",
        "genero":"peleas multijugador",
        "descripcion":"Super Smash Bros. Ultimate es un juego de peleas con un estilo unico, donde cada personaje pertenece a una de las tantas sagas exitosas de Nintendo, pelea junto o en contra tus amigos en este divertido juego de pelea hecho para fiestas",
        "precio": 60000,
    },
    {
        "id":"g07",
        "nombre": "God of War: Ragnarok",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717455567/imagen_2024-06-03_185923207_epmmco.png",
        "desarrolladores": "Santa Monica Studio",
        "genero":"RPG aventura Hack n' Slash",
        "descripcion":"Recorre de inicio a fin un mundo ambientado en la mitologia Nordica, siguiendo los problemas y aventuras de Kratos y su hijo Atreus en busca de tratar con los mayores dioses de Midgard",
        "precio": 50000,
    },
    {
        "id":"g08",
        "nombre": "EA Sports FC 24",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717535935/imagen_2024-06-04_171852384_iuhey9.png",
        "desarrolladores": "EA",
        "genero":"Deportes Multijugador",
        "descripcion":"EA Sports FC 24 es un videojuego de fútbol, desarrollado por EA, y publicado por EA Sports. Este juego marca la primera entrega de la serie EA Sports FC, tras la conclusión de la asociación de EA con FIFA.",
        "precio": 50000,
    },
    {
        "id":"g09",
        "nombre": "Call of duty: Modern Warfare 3",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717514781/carlosdutibase_elqbhp.jpg",
        "desarrolladores": "Infinity ward",
        "genero":"Shooter Multijugador",
        "descripcion":"Ultima entrega de la aclamada saga Call of duty, con una gran variedad de modos de juego, despliegate para competir con miles de jugadores en linea o contra tus amigos en local",
        "precio": 50000,
    },
    
];
const consoles = [
    {
        "id":"c01",
        "nombre": "Xbox XS",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717515769/xbox_drfhbj.webp",
        "creadores":"Microsoft",
        "precio":350000,
    },
    {
        "id":"c02",
        "nombre": "PlayStation 5",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717515719/play5_qrp1us.jpg",
        "creadores":"Sony",
        "precio":500000,
    },
    {
        "id":"c03",
        "nombre": "Nintendo Switch",
        "imagen":"https://res.cloudinary.com/dmhjhzpwk/image/upload/v1717515806/switch_csck0k.avif",
        "creadores":"Nintendo",
        "precio":300000,
    },
];
module.exports = {
    games , consoles
}